// Generated by embyExternalUrl-Manager.
const redirectConfig = {
  enable: {{REDIRECT_ENABLED}},
  enablePartStreamPlayOrDownload: {{ENABLE_PART_STREAM}},
  enableVideoTranscodePlay: {{ENABLE_VIDEO_TRANSCODE}},
};
const routeCacheConfig = {
  enable: {{ROUTE_CACHE_ENABLED}},
  enableL2: false,
  keyExpression: "r.uri:r.args.path:r.args.mediaIndex:r.args.partIndex",
};
const routeRule = [];
const mediaPathMapping = {{MEDIA_PATH_MAPPING}};
const alistRawUrlMapping = [];

export default {
  redirectConfig,
  routeCacheConfig,
  routeRule,
  mediaPathMapping,
  alistRawUrlMapping,
};
