// Generated by embyExternalUrl-Manager. Manual edits may be overwritten.
import commonConfig from "./config/constant-common.js";
import mountConfig from "./config/constant-mount.js";
import proConfig from "./config/constant-pro.js";
import symlinkConfig from "./config/constant-symlink.js";
import strmConfig from "./config/constant-strm.js";
import transcodeConfig from "./config/constant-transcode.js";

const plexHost = {{PLEX_SERVER_URL}};
const mediaMountPath = {{MEDIA_MOUNT_PATHS}};

function getPlexHost(r) { return plexHost; }
function getTranscodeEnable(r) { return transcodeConfig.transcodeConfig.enable; }

export default {
  plexHost,
  mediaMountPath,
  strHead: commonConfig.strHead,
  alistAddr: mountConfig.alistAddr,
  alistToken: mountConfig.alistToken,
  alistSignEnable: mountConfig.alistSignEnable,
  alistSignExpireTime: mountConfig.alistSignExpireTime,
  alistPublicAddr: mountConfig.alistPublicAddr,
  clientSelfAlistRule: mountConfig.clientSelfAlistRule,
  redirectCheckEnable: mountConfig.redirectCheckEnable,
  fallbackUseOriginal: mountConfig.fallbackUseOriginal,
  redirectConfig: proConfig.redirectConfig,
  routeCacheConfig: proConfig.routeCacheConfig,
  routeRule: proConfig.routeRule,
  mediaPathMapping: proConfig.mediaPathMapping,
  alistRawUrlMapping: proConfig.alistRawUrlMapping,
  symlinkRule: symlinkConfig.symlinkRule,
  redirectStrmLastLinkRule: strmConfig.redirectStrmLastLinkRule,
  transcodeConfig: transcodeConfig.transcodeConfig,
  getPlexHost,
  getTranscodeEnable,
};
