// Generated by embyExternalUrl-Manager.
const alistAddr = {{OPENLIST_URL}};
const alistToken = {{OPENLIST_TOKEN}};
const alistSignEnable = {{SIGN_ENABLED}};
const alistSignExpireTime = {{SIGN_EXPIRE_HOURS}};
const alistPublicAddr = {{OPENLIST_PUBLIC_URL}};
const clientSelfAlistRule = [];
const redirectCheckEnable = false;
const fallbackUseOriginal = {{FALLBACK_USE_ORIGINAL}};

export default {
  alistAddr,
  alistToken,
  alistSignEnable,
  alistSignExpireTime,
  alistPublicAddr,
  clientSelfAlistRule,
  redirectCheckEnable,
  fallbackUseOriginal,
};
