server_name default;
## SSL SETTINGS ##
listen [::]:{{PROXY_HTTPS_PORT}} ssl;
listen {{PROXY_HTTPS_PORT}} ssl;
http2 on;
ssl_session_timeout 30m;
ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1;
ssl_certificate      /etc/nginx/conf.d/cert/fullchain.pem;
ssl_certificate_key  /etc/nginx/conf.d/cert/privkey.key;
ssl_session_cache shared:SSL:10m;
error_page 497 =307 https://$host:$server_port$request_uri;
