// Generated by embyExternalUrl-Manager.
import commonConfig from "./constant-common.js";

const strHead = commonConfig.strHead;
const alistAddr = {{OPENLIST_URL}};
const alistToken = {{OPENLIST_TOKEN}};
const alistSignEnable = {{SIGN_ENABLED}};
const alistSignExpireTime = {{SIGN_EXPIRE_HOURS}};
const alistPublicAddr = {{OPENLIST_PUBLIC_URL}};
const clientSelfAlistRule = [
  [2, strHead["115"], alistPublicAddr]
];
const redirectCheckEnable = false;
const fallbackUseOriginal = {{FALLBACK_USE_ORIGINAL}};

export default {
  alistAddr,
  alistToken,
  alistSignEnable,
  alistSignExpireTime,
  alistPublicAddr,
  clientSelfAlistRule,
  redirectCheckEnable,
  fallbackUseOriginal,
};
