// Generated by embyExternalUrl-Manager.
import commonConfig from "./constant-common.js";
import mountConfig from "./constant-mount.js";

const strHead = commonConfig.strHead;
const ruleRef = commonConfig.ruleRef;
const alistPublicAddr = mountConfig.alistPublicAddr;

const redirectConfig = {
  enable: {{REDIRECT_ENABLED}},
  enableVideoLivePlay: {{EMBY_VIDEO_LIVE_PLAY}},
  enableVideoStreamPlay: {{EMBY_VIDEO_STREAM_PLAY}},
  enableAudioStreamPlay: {{EMBY_AUDIO_STREAM_PLAY}},
  enableItemsDownload: {{EMBY_ITEMS_DOWNLOAD}},
  enableSyncDownload: {{EMBY_SYNC_DOWNLOAD}},
};

const routeCacheConfig = {
  enable: {{ROUTE_CACHE_ENABLED}},
  enableL2: false,
  keyExpression: "r.uri:r.args.MediaSourceId",
};

const routeRule = [];
const mediaPathMapping = {{MEDIA_PATH_MAPPING}};
const alistRawUrlMapping = [];

export default {
  redirectConfig,
  routeCacheConfig,
  routeRule,
  mediaPathMapping,
  alistRawUrlMapping,
};
